// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbAbonosPorPrestamos_Bitacora
    {
        public int abpr_Id { get; set; }
        public int pres_Id { get; set; }
        public decimal abpr_MontoAbonado { get; set; }
        public DateTime abpr_Fecha { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime abpr_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? abpr_FechaModificacion { get; set; }
        public bool abpr_DeducidoEnPlanilla { get; set; }
        public string accion { get; set; }
    }
}