// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbActividades
    {
        public tbActividades()
        {
            tbActividadesPorEtapas = new HashSet<tbActividadesPorEtapas>();
            tbCostoPorActividad = new HashSet<tbCostoPorActividad>();
        }

        public int acti_Id { get; set; }
        public string acti_Descripcion { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? acti_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? acti_FechaModificacion { get; set; }
        public bool? acti_Estado { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public int codigo { get; set; }

        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbActividadesPorEtapas> tbActividadesPorEtapas { get; set; }
        public virtual ICollection<tbCostoPorActividad> tbCostoPorActividad { get; set; }
    }
}