// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbAlertas
    {
        public int aler_Id { get; set; }
        public DateTime aler_Fecha { get; set; }
        public string aler_Descripcion { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? aler_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? aler_FechaModificacion { get; set; }
        public bool? aler_Estado { get; set; }





        [NotMapped]
        public int usua_Id { get; set; }

        [NotMapped]
        public int tian_Id { get; set; }
        [NotMapped]
        public string aler_Ruta { get; set; }


        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}