// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbBienesRaices
    {
        public int bien_Id { get; set; }
        public string bien_Desripcion { get; set; }
        public int? pcon_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime bien_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? bien_FechaModificacion { get; set; }
        public bool? bien_Estado { get; set; }
        public string bien_Imagen { get; set; }
        public decimal? bien_Precio { get; set; }
        [NotMapped]
        public string proy_DireccionExacta { get; set; }
        [NotMapped]
        public string terr_Descripcion { get; set; }
        [NotMapped]
        public string terr_Direccion { get; set; }

        [NotMapped]
        public string terr_Area { get; set; }
        [NotMapped]
        public string terr_LinkUbicacion { get; set; }

        [NotMapped]
        public int terr_Id { get; set; }
        [NotMapped]
        public int proy_Id { get; set; }


        [NotMapped]
        public string proy_Nombre { get; set; }


        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        [NotMapped]
        public string descripcion { get; set; }

        [NotMapped]
        public int DocumentoId { get; set; }
        [NotMapped]
        public string DescripcionDocumento { get; set; }
        [NotMapped]
        public DateTime? DocumentoFechaCreacion { get; set; }
        [NotMapped]
        public int TipoDocumentoId { get; set; }
        [NotMapped]
        public string TipoDocumentoDescripcion { get; set; }
        [NotMapped]
        public int Codigo { get; set; }
        [NotMapped]
        public int Codigo2 { get; set; }
        [NotMapped]
        public string DocumentoImagen { get; set; }
        [NotMapped]
        public string dobt_DescipcionDocumento { get; set; }

        public virtual tbProyectosConstruccionBienesRaices pcon { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}