// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbBitacoraInsumos
    {
        public string bita_Accion { get; set; }
        public int? bita_Usuario { get; set; }
        public DateTime? bita_FechaAccion { get; set; }
        public int insu_Id { get; set; }
        public int prov_Id { get; set; }
        public string unme_Id { get; set; }
        public string inpp_Observacion { get; set; }
        public int inpp_Preciocompra { get; set; }
    }
}