// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbBitacoraTasasCambio
    {
        public string bita_Accion { get; set; }
        public int? bita_Usuario { get; set; }
        public DateTime bita_FechaAccion { get; set; }
        public int taca_Id { get; set; }
        public int mone_A { get; set; }
        public decimal taca_ValorA { get; set; }
        public int mone_B { get; set; }
        public decimal taca_ValorB { get; set; }
        public bool taca_Estado { get; set; }
    }
}