// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbBodegasPorInsumo
    {
        public int bopi_Id { get; set; }
        public int? inpp_Id { get; set; }
        public int? bode_Id { get; set; }
        public int? bopi_Stock { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? bopi_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? bopi_FechaModificacion { get; set; }
        public decimal? bopi_Precio { get; set; }

        [NotMapped]
        public string bode_Descripcion { get; set; }

        public virtual tbBodegas bode { get; set; }
        public virtual tbInsumosPorProveedores inpp { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}