// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbCategorias
    {
        public tbCategorias()
        {
            tbSubcategorias = new HashSet<tbSubcategorias>();
        }

        public int cate_Id { get; set; }
        public string cate_Descripcion { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime cate_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? cate_FechaModificacion { get; set; }
        public bool? cate_Estado { get; set; }

        [NotMapped]
        public string usuarioCreacion { get; set; }

        [NotMapped]
        public string usuarioModificacion { get; set; }

        [NotMapped]
        public string codigo { get; set; }

        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbSubcategorias> tbSubcategorias { get; set; }
    }
}