// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbCategoriasViaticos
    {
        public tbCategoriasViaticos()
        {
            tbViaticosDetalles = new HashSet<tbViaticosDetalles>();
        }

        public int cavi_Id { get; set; }
        public string cavi_Descripcion { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime cavi_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? cavi_FechaModificacion { get; set; }
        public bool? cavi_Estado { get; set; }

        [NotMapped]
        public string usuarioCreacion { get; set; }

        [NotMapped]
        public string usuarioModificacion { get; set; }

        [NotMapped]
        public string codigo { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbViaticosDetalles> tbViaticosDetalles { get; set; }
    }
}