// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbCategoriasViaticos_Bitacora
    {
        public int? cavi_Id { get; set; }
        public string cavi_Descripcion { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? cavi_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? cavi_FechaModificacion { get; set; }
        public bool? cavi_Estado { get; set; }
        public string accion { get; set; }
    }
}