// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbCiudades
    {
        public tbCiudades()
        {
            tbClientes = new HashSet<tbClientes>();
            tbEmpleados = new HashSet<tbEmpleados>();
            tbProveedores = new HashSet<tbProveedores>();
            tbProyectos = new HashSet<tbProyectos>();
        }

        public int ciud_Id { get; set; }
        public string ciud_Codigo { get; set; }
        public string ciud_Descripcion { get; set; }
        public int esta_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime ciud_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? ciud_FechaModificiacion { get; set; }

        [NotMapped]
        public string esta_Nombre { get; set; }


        [NotMapped]
        public string Codigo { get; set; }

        [NotMapped]
        public string pais_Id { get; set; }
        [NotMapped]
        public string pais_Nombre { get; set; }

        [NotMapped]
        public string ciud_usua_Creacion { get; set; }
        [NotMapped]
        public string ciud_usua_Modificacion { get; set; }

        public virtual tbEstados esta { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientes { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbProveedores> tbProveedores { get; set; }
        public virtual ICollection<tbProyectos> tbProyectos { get; set; }
    }
}