// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbComprasDetallesDirecciones
    {
        public int codd_Id { get; set; }
        public int codt_Id { get; set; }
        public int codd_Cantidad { get; set; }
        public bool codd_ProyectoOBodega { get; set; }
        public int codd_Boat_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime codd_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? codd_FechaModificacion { get; set; }

        public virtual tbComprasDetalle codt { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}