// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbCostoPorActividad
    {
        public int copc_Id { get; set; }
        public int? unme_Id { get; set; }
        public int? acti_Id { get; set; }
        public decimal? copc_Valor { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? copc_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? copc_FechaModificacion { get; set; }
        public int? copc_EstadoActividad { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string UnidadDeMedida { get; set; }

        [NotMapped]
        public string Actividad { get; set; }

        [NotMapped]
        public string UsuarioCreacion { get; set; }

        [NotMapped]
        public string UsuarioModifica { get; set; }

        public virtual tbActividades acti { get; set; }
        public virtual tbUnidadesMedida unme { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}