// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbComprasDetallesDireccionesPorMaquinaria
    {
        public int codm_Id { get; set; }
        public int codt_Id { get; set; }
        public string codm_HorasRenta { get; set; }
        public int acet_Id { get; set; }
        public int? codm_Cantidad { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime codm_FechaCreacion { get; set; }
        public int? usua_Modficacion { get; set; }
        public DateTime? codm_FechaModificacion { get; set; }

        public virtual tbActividadesPorEtapas acet { get; set; }
        public virtual tbComprasDetalle codt { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModficacionNavigation { get; set; }
    }
}