// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbCostoPorActividad_Bitacora
    {
        public int? copc_Id { get; set; }
        public int? unme_Id { get; set; }
        public int? acti_Id { get; set; }
        public int? copc_Valor { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? copc_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? copc_FechaModificacion { get; set; }
        public bool? copc_EstadoActividad { get; set; }
        public string accion { get; set; }
    }
}