// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbDeducciones
    {
        public tbDeducciones()
        {
            tbDeduccionesPorEmpleados = new HashSet<tbDeduccionesPorEmpleados>();
            tbDeduccionesPorPlanilla = new HashSet<tbDeduccionesPorPlanilla>();
        }

        public int dedu_Id { get; set; }
        public string dedu_Descripcion { get; set; }
        public decimal dedu_Porcentaje { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime dedu_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? dedu_FechaModificacion { get; set; }
        public bool? dedu_Estado { get; set; }
        public bool? dedu_EsMontoFijo { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }

        [NotMapped]
        public string usuaModificacion { get; set; }

        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbDeduccionesPorEmpleados> tbDeduccionesPorEmpleados { get; set; }
        public virtual ICollection<tbDeduccionesPorPlanilla> tbDeduccionesPorPlanilla { get; set; }
    }
}