// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbDeducciones_Bitacora
    {
        public int? dedu_Id { get; set; }
        public string dedu_Descripcion { get; set; }
        public decimal? dedu_Porcentaje { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? dedu_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? dedu_FechaModificacion { get; set; }
        public bool? dedu_Estado { get; set; }
        public bool? dedu_EsMontoFijo { get; set; }
        public string accion { get; set; }
    }
}