// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbDocumentosBienRaiz
    {
        public int dobt_Id { get; set; }
        public string dobt_DescipcionDocumento { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime dobt_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? dobt_FechaModificacion { get; set; }
        public bool? dobt_Estado { get; set; }
        public int? dobt_Terreno_O_BienRaizId { get; set; }
        public bool? dobt_Terreno_O_BienRaizbit { get; set; }
        public string dobt_Imagen { get; set; }
        public int? tido_Id { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string tido_Descripcion { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public string bien_Desripcion { get; set; }
        [NotMapped]
        public string terr_Descripcion { get; set; }
        [NotMapped]
        public string UsuarioCreacionNombre { get; set; }
        [NotMapped]
        public string UsuarioModificadorNombre { get; set; }

        public virtual tbTiposDocumentos tido { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}