// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbEmpresasBienesRaices
    {
        public tbEmpresasBienesRaices()
        {
            tbAgentesBienesRaices = new HashSet<tbAgentesBienesRaices>();
        }
        public int embr_Id { get; set; }
        public string embr_Nombre { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime embr_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? embr_FechaModificacion { get; set; }
        public bool? embr_Estado { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public string embr_ContactoA { get; set; }
        [NotMapped]
        public string embr_ContactoB { get; set; }
        [NotMapped]
        public string embr_TelefonoA { get; set; }
        [NotMapped]
        public string embr_TelefonoB { get; set; }

        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbAgentesBienesRaices> tbAgentesBienesRaices { get; set; }
    }
}