// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbActividadesPorEtapas = new HashSet<tbActividadesPorEtapas>();
            tbComprasEncabezado = new HashSet<tbComprasEncabezado>();
            tbCotizaciones = new HashSet<tbCotizaciones>();
            tbDeduccionesPorEmpleados = new HashSet<tbDeduccionesPorEmpleados>();
            tbDocumentos = new HashSet<tbDocumentos>();
            tbEtapasPorProyectos = new HashSet<tbEtapasPorProyectos>();
            tbPlanillaDetalles = new HashSet<tbPlanillaDetalles>();
            tbPrestamos = new HashSet<tbPrestamos>();
            tbPresupuestosEncabezado = new HashSet<tbPresupuestosEncabezado>();
            tbUsuarios = new HashSet<tbUsuarios>();
            tbViaticosEncabezados = new HashSet<tbViaticosEncabezados>();
        }

        public int empl_Id { get; set; }
        public string empl_DNI { get; set; }
        public string empl_Nombre { get; set; }
        public string empl_Apellido { get; set; }
        public string empl_CorreoElectronico { get; set; }
        public string empl_Telefono { get; set; }
        public string empl_Sexo { get; set; }
        public DateTime empl_FechaNacimiento { get; set; }
        public decimal? empl_Salario { get; set; }
        public int ciud_Id { get; set; }
        public int civi_Id { get; set; }
        public int carg_Id { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? empl_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? empl_FechaModificacion { get; set; }
        public bool? empl_Estado { get; set; }
        public int? frec_Id { get; set; }
        public string empl_NoBancario { get; set; }
        public int? banc_Id { get; set; }
        public string empl_Imagen { get; set; }
        public string empl_ObservacionActivar { get; set; }
        public string empl_ObservacionInactivar { get; set; }
        public decimal empl_Prestaciones { get; set; }
        public decimal empl_OtrasRemuneraciones { get; set; }
        [NotMapped]
        public string deducciones_Ids { get; set; }

        [NotMapped]
        public decimal salarioPromedio { get; set; }
        [NotMapped]
        public string deduccionesJSON { get; set; }
        [NotMapped]
        public string banco { get; set; }

        [NotMapped]
        public string frecuencia { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }

        [NotMapped]
        public string usuaModificacion { get; set; }

        [NotMapped]
        public string cargo { get; set; }

        [NotMapped]
        public string estadoCivil { get; set; }

        [NotMapped]
        public string ciudad { get; set; }
        [NotMapped]
        public int? esta_Id { get; set; }
        [NotMapped]
        public string estado { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string empleado { get; set; }

        [NotMapped]
        public string empl_NombreCompleto { get; set; }

        public virtual tbBancos banc { get; set; }
        public virtual tbCargos carg { get; set; }
        public virtual tbCiudades ciud { get; set; }
        public virtual tbEstadosCiviles civi { get; set; }
        public virtual tbFrecuencias frec { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbActividadesPorEtapas> tbActividadesPorEtapas { get; set; }
        public virtual ICollection<tbComprasEncabezado> tbComprasEncabezado { get; set; }
        public virtual ICollection<tbCotizaciones> tbCotizaciones { get; set; }
        public virtual ICollection<tbDeduccionesPorEmpleados> tbDeduccionesPorEmpleados { get; set; }
        public virtual ICollection<tbDocumentos> tbDocumentos { get; set; }
        public virtual ICollection<tbEtapasPorProyectos> tbEtapasPorProyectos { get; set; }
        public virtual ICollection<tbPlanillaDetalles> tbPlanillaDetalles { get; set; }
        public virtual ICollection<tbPrestamos> tbPrestamos { get; set; }
        public virtual ICollection<tbPresupuestosEncabezado> tbPresupuestosEncabezado { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
        public virtual ICollection<tbViaticosEncabezados> tbViaticosEncabezados { get; set; }
    }
}