// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbEstadosProyectos
    {
        public tbEstadosProyectos()
        {
            tbActividadesPorEtapas = new HashSet<tbActividadesPorEtapas>();
            tbProyectos = new HashSet<tbProyectos>();
        }

        public int espr_Id { get; set; }
        public string espr_Descripcion { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? espr_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? espr_FechaModificacion { get; set; }
        public bool? espr_Estado { get; set; }

        [NotMapped]
        public string UsuaModificacion { get; set; }
        [NotMapped]
        public string UsuaCreacion { get; set; }

        [NotMapped]
        public int codigo { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbActividadesPorEtapas> tbActividadesPorEtapas { get; set; }
        public virtual ICollection<tbProyectos> tbProyectos { get; set; }
    }
}