// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbEtapas
    {
        public tbEtapas()
        {
            tbEtapasPorProyectos = new HashSet<tbEtapasPorProyectos>();
        }

        public int etap_Id { get; set; }
        public string etap_Descripcion { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? etap_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? etap_FechaModificacion { get; set; }
        public bool? etap_Estado { get; set; }

        [NotMapped]
        public string codigo { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEtapasPorProyectos> tbEtapasPorProyectos { get; set; }
    }
}