// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbFletesEncabezado
    {
        public tbFletesEncabezado()
        {
            tbFletesControlCalidad = new HashSet<tbFletesControlCalidad>();
            tbFletesDetalle = new HashSet<tbFletesDetalle>();
            tbIncidenciasPorFletes = new HashSet<tbIncidenciasPorFletes>();
        }

        [NotMapped]
        public string codigo { get; set; }
        [NotMapped]
        public string usuarioCreacion { get; set; }
        [NotMapped]
        public string usuarioModificacion { get; set; }
        [NotMapped]
        public string Encargado { get; set; }
        [NotMapped]
        public string Supervisorllegada { get; set; }
        [NotMapped]
        public string Supervisorsalida { get; set; }
        [NotMapped]
        public string Destino { get; set; }
        [NotMapped]
        public string Estado { get; set; }
        [NotMapped]
        public string Salida { get; set; }
        [NotMapped]
        public bool flde_llegada { get; set; }

        public int flen_Id { get; set; }
        public DateTime flen_FechaHoraSalida { get; set; }
        public DateTime flen_FechaHoraEstablecidaDeLlegada { get; set; }
        public DateTime? flen_FechaHoraLlegada { get; set; }
        public bool flen_Estado { get; set; }
        public bool flen_DestinoProyecto { get; set; }
        public int boll_Id { get; set; }
        public int boat_Id { get; set; }
        [NotMapped]
        public int boas_Id { get; set; }

        [NotMapped]
        public bool? flen_SalidaProyecto { get; set; }

        [NotMapped]
        public string boat_Descripcion { get; set; }
        [NotMapped]
        public int proy_Id { get; set; }
        [NotMapped]
        public int proy_IdSalida { get; set; }
        [NotMapped]
        public string proy_Descripcion { get; set; }
        [NotMapped]
        public string proy_Nombre { get; set; }
        [NotMapped]
        public int acti_Id { get; set; }
        [NotMapped]
        public int etap_Id { get; set; }
        [NotMapped]
        public string acti_Descripcion { get; set; }
        [NotMapped]
        public string etap_Descripcion { get; set; }

        [NotMapped]

        public int? etpr_Id { get; set; }
        [NotMapped]
        public string? insu_Observacion { get; set; }
        [NotMapped]
        public int? mate_Id { get; set; }
        public int emtr_Id { get; set; }
        public int emss_Id { get; set; }
        public int emsl_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime flen_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? flen_FechaModificacion { get; set; }
        public int? flen_EstadoFlete { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }


        //tbEstadosProyectos SALIDA
        [NotMapped]
        public int acti_Id1 { get; set; }
        [NotMapped]
        public int etap_Id1 { get; set; }
        [NotMapped]
        public string acti_Descripcion1 { get; set; }
        [NotMapped]
        public string etap_Descripcion1 { get; set; }


        [NotMapped]
        public string flen_ComprobanteLLegada { get; set; }


        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbFletesControlCalidad> tbFletesControlCalidad { get; set; }
        public virtual ICollection<tbFletesDetalle> tbFletesDetalle { get; set; }
        public virtual ICollection<tbIncidenciasPorFletes> tbIncidenciasPorFletes { get; set; }
    }
}