// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbFletesControlCalidad
    {
        public int flcc_Id { get; set; }
        public string flcc_DescripcionIncidencia { get; set; }
        public DateTime flcc_FechaHoraIncidencia { get; set; }
        public int flen_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime flcc_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? flcc_FechaModificacion { get; set; }
        public bool? flcc_Estado { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public DateTime flen_FechaHoraSalida { get; set; }
        [NotMapped]
        public DateTime flen_FechaHoraEstablecidaDeLlegada { get; set; }
        [NotMapped]
        public bool? flen_Estado { get; set; }
        [NotMapped]
        public bool? flen_DestinoProyecto { get; set; }

        public virtual tbFletesEncabezado flen { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}