// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbFletesDetalle
    {
        public int flde_Id { get; set; }
        public int flde_Cantidad { get; set; }
        public int flen_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime flde_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? flde_FechaModificacion { get; set; }
        public int inpp_Id { get; set; }
        public bool? flde_llegada { get; set; }

        [NotMapped]
        public string bode_Descripcion { get; set; }
        [NotMapped]
        public bool flde_TipodeCarga { get; set; }
        [NotMapped]
        public int bode_Id { get; set; }
        [NotMapped]
        public int bopi_Stock { get; set; }
        [NotMapped]
        public int codigo { get; set; }
        [NotMapped]
        public string prov_Descripcion { get; set; }
        [NotMapped]
        public string insu_Descripcion { get; set; }

        [NotMapped]
        public string inpp_Observacion { get; set; }

        [NotMapped]
        public string mate_Descripcion { get; set; }


        [NotMapped]
        public string unme_Nombre { get; set; }
        [NotMapped]
        public int unme_Id { get; set; }

        [NotMapped]
        public string unme_Nomenclatura { get; set; }
        [NotMapped]
        public string equs_Nombre { get; set; }
        [NotMapped]
        public string equs_Descripcion { get; set; }


        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }



        [NotMapped]

        public int? proy_Id { get; set; }
        [NotMapped]
        public string? proy_Nombre { get; set; }
        [NotMapped]
        public string? proy_Descripcion { get; set; }
        [NotMapped]

        public int? etpr_Id { get; set; }
        [NotMapped]
        public string? etap_Descripcion { get; set; }
        [NotMapped]

        public int? acti_Id { get; set; }
        [NotMapped]
        public string? acti_Descripcion { get; set; }
        [NotMapped]
        public string? insu_Observacion { get; set; }
        [NotMapped]
        public int? mate_Id { get; set; }

        [NotMapped]
        public int acti_Id1 { get; set; }
        [NotMapped]
        public int etap_Id1 { get; set; }
        [NotMapped]
        public string acti_Descripcion1 { get; set; }
        [NotMapped]
        public string etap_Descripcion1 { get; set; }

        [NotMapped]
        public string flen_ComprobanteLLegada { get; set; }

        public virtual tbFletesEncabezado flen { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}