// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbImpuestos
    {
        public int impu_Id { get; set; }
        public decimal? impu_Porcentaje { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? impu_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? impu_FechaModificacion { get; set; }

        [NotMapped]
        public string codigo { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }

        [NotMapped]
        public string usuaModificacion { get; set; }

        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}