// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbImagenesPorGestionesAdicionales
    {
        public int Imge_Id { get; set; }
        public string Imge_Imagen { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime Imge_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? Imge_FechaModificacion { get; set; }
        public bool? Imge_Estado { get; set; }
        public int? adic_Id { get; set; }

        [NotMapped]
        public int arch_Id { get; set; }
        [NotMapped]
        public string arch_Nombre { get; set; }
        [NotMapped]
        public string arch_Ruta { get; set; }
        [NotMapped]
        public int? Proy_Id { get; set; }
        [NotMapped]
        public int? inci_Id { get; set; }
        [NotMapped]
        public DateTime arch_FechaCreacion { get; set; }
        [NotMapped]
        public DateTime? arch_FechaModificacion { get; set; }
        [NotMapped]
        public bool? arch_Estado { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        public virtual tbGestionesAdicionales adic { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}