// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbImpuestos_Bitacora
    {
        public int? impu_Id { get; set; }
        public decimal? impu_Porcentaje { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? imp_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? impu_FechaModificacion { get; set; }
        public string Acciones { get; set; }
    }
}