// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbImagenesPorProcesosVentas
    {
        public int impr_Id { get; set; }
        public int btrp_Id { get; set; }
        public string impr_Imagen { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime impr_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? impr_FechaModificacion { get; set; }

        [NotMapped]
        public string dobt_DescipcionDocumento { get; set; }
        [NotMapped]
        public int? dobt_Id { get; set; }
        [NotMapped]
        public int? dobt_Terreno_O_BienRaizId { get; set; }
        [NotMapped]
        public bool? dobt_Terreno_O_BienRaizbit { get; set; }
        [NotMapped]
        public string dobt_Imagen { get; set; }
        [NotMapped]
        public int tido_Id { get; set; }
        [NotMapped]
        public string tido_Descripcion { get; set; }

        [NotMapped]
        public string codigo { get; set; }

        public virtual tbProcesosVentas btrp { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}