// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbIncidenciasPorActividades
    {
        public int inac_Id { get; set; }
        public int? acet_Id { get; set; }
        public int? inci_Id { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? inac_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? inac_FechaModificacion { get; set; }
        public bool? inac_Estado { get; set; }

        public virtual tbActividadesPorEtapas acet { get; set; }
        public virtual tbIncidentes inci { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}