// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbIncidentes
    {
        public tbIncidentes()
        {
            tbImagenesPorIncidencias = new HashSet<tbImagenesPorIncidencias>();
            tbIncidenciasPorActividades = new HashSet<tbIncidenciasPorActividades>();
        }

        public int inci_Id { get; set; }
        public string inci_Descripcion { get; set; }
        public DateTime inci_Fecha { get; set; }
        public decimal inci_Costo { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string imin_Imagen { get; set; }

        [NotMapped] //
        public DateTime? imin_FechaModificacion { get; set; }

        [NotMapped] //
        public DateTime? imin_FechaCreacion { get; set; }

        public int empl_Id { get; set; }
        public int etpr_Id { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? inci_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? inci_FechaModificacion { get; set; }
        public bool? inci_Estado { get; set; }
        public int? acet_Id { get; set; }

        [NotMapped]
        public string usuario_Creacion { get; set; }
        [NotMapped]
        public string usuario_Modificacion { get; set; }

        [NotMapped]
        public int proy_Id { get; set; }
        [NotMapped]
        public string proy_Nombre { get; set; }
        [NotMapped]
        public string proy_Descripcion { get; set; }
        [NotMapped]
        public DateTime proy_FechaInicio { get; set; }
        [NotMapped]
        public DateTime proy_FechaFin { get; set; }

        [NotMapped]

        public string etap_Descripcion { get; set; }

        public string acti_Descripcion { get; set; }
        [NotMapped]
        public int acet_Cantidad { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public string etap_Id { get; set; }

        public virtual tbActividadesPorEtapas acet { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbImagenesPorIncidencias> tbImagenesPorIncidencias { get; set; }
        public virtual ICollection<tbIncidenciasPorActividades> tbIncidenciasPorActividades { get; set; }
    }
}