// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbInsumosPorActividades
    {
        public int inpa_Id { get; set; }
        public int acet_Id { get; set; }
        public int inpa_stock { get; set; }
        public decimal inpa_PrecioCompra { get; set; }
        public decimal inpa_Rendimiento { get; set; }
        public int inpa_Desperdicio { get; set; }


        public bool inpa_EsCompra { get; set; }
        public int? inpa_ActividadLlenado { get; set; }

        public string? inpa_FormulaRendimiento { get; set; }

        public string? inpa_StockFormula { get; set; }
        public string? inpa_PrecioCompraFormula { get; set; }
        public DateTime inpa_Fecha { get; set; }
        public int inpp_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime inpa_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? inpa_FechaModificacion { get; set; }
        public bool? inpa_Estado { get; set; }

        [NotMapped]
        public int row { get; set; }
        [NotMapped]
        public string insu_Descripcion { get; set; }
        [NotMapped]
        public string equs_Nombre { get; set; }
        [NotMapped]
        public int eqpp_Id { get; set; }
        [NotMapped]
        public string equs_Descripcion { get; set; }
        [NotMapped]
        public string unme_Nombre { get; set; }
        [NotMapped]
        public string unme_Nomenclatura { get; set; }
        [NotMapped]
        public decimal bopi_Stock { get; set; }
        [NotMapped]
        public string mate_Descripcion { get; set; }
        [NotMapped]
        public int prov_Id { get; set; }
        [NotMapped]
        public string prov_Descripcion { get; set; }
        [NotMapped]
        public string suca_Descripcion { get; set; }
        [NotMapped]
        public string cate_Descripcion { get; set; }
        [NotMapped]
        public string inpp_Observacion { get; set; }
        [NotMapped]
        public decimal inpp_Preciocompra { get; set; }
        [NotMapped]
        public string bode_Descripcion { get; set; }
        [NotMapped]
        public int bode_Id { get; set; }
        

        public virtual tbActividadesPorEtapas acet { get; set; }
        public virtual tbInsumosPorProveedores inpp { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}