// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbIncidenciasPorFletes
    {
        public int infl_Id { get; set; }
        public int inci_Id { get; set; }
        public int flen_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime infl_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? infl_FechaModificacion { get; set; }


        public virtual tbFletesEncabezado flen { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}