// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbInsumosPorProveedores
    {
        public tbInsumosPorProveedores()
        {
            tbBodegasPorInsumo = new HashSet<tbBodegasPorInsumo>();
            tbInsumosPorActividades = new HashSet<tbInsumosPorActividades>();
        }

        public int inpp_Id { get; set; }
        public int? insu_Id { get; set; }
        public int? prov_Id { get; set; }
        public decimal? inpp_Preciocompra { get; set; }
        public int? unme_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime inpp_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? inpp_FechaModificacion { get; set; }
        public string inpp_Observacion { get; set; }

        [NotMapped]
        public int codigo { get; set; }
        [NotMapped]
        public string mate_Descripcion { get; set; }
        [NotMapped]
        public string insu_Descripcion { get; set; }
        [NotMapped]
        public string prov_Descripcion { get; set; }
        [NotMapped]
        public string unme_Nombre { get; set; }
        [NotMapped]
        public string unme_Nomenclatura { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public int bode_Id { get; set; }
        [NotMapped]
        public int suca_Id { get; set; }
        [NotMapped]
        public int mate_Id { get; set; }
        [NotMapped]
        public int cate_Id { get; set; }
        [NotMapped]
        public string cate_Descripcion { get; set; }
        [NotMapped]
        public string suca_Descripcion { get; set; }
        [NotMapped]
        public string bode_Descripcion { get; set; }
        [NotMapped]
        public decimal bopi_Stock { get; set; }
        [NotMapped]
        public decimal inpa_Stock { get; set; }
        [NotMapped]
        public bool inpa_Recomendado { get; set; }

        public virtual tbInsumos insu { get; set; }
        public virtual tbProveedores prov { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbBodegasPorInsumo> tbBodegasPorInsumo { get; set; }
        public virtual ICollection<tbInsumosPorActividades> tbInsumosPorActividades { get; set; }
    }
}