// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbInsumos
    {
        public tbInsumos()
        {
            tbInsumosPorMedidas = new HashSet<tbInsumosPorMedidas>();
            tbInsumosPorProveedores = new HashSet<tbInsumosPorProveedores>();
        }

        public int insu_Id { get; set; }
        public int suca_Id { get; set; }
        public string insu_Descripcion { get; set; }
        public string insu_Observacion { get; set; }
        public int mate_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime insu_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? insu_FechaModificacion { get; set; }
        public bool? insu_Estado { get; set; }
        public decimal? insu_UltimoPrecioUnitario { get; set; }

        [NotMapped]
        public string insumos { get; set; }

        [NotMapped]
        public string suca_Descripcion { get; set; }

        [NotMapped]
        public string mate_Descripcion { get; set; }

        [NotMapped]
        public int codigo { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public string cate_Descripcion { get; set; }

        [NotMapped]
        public int cate_Id { get; set; }

        public virtual tbMateriales mate { get; set; }
        public virtual tbSubcategorias suca { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumosPorMedidas> tbInsumosPorMedidas { get; set; }
        public virtual ICollection<tbInsumosPorProveedores> tbInsumosPorProveedores { get; set; }
    }
}