// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbInsumosPorMedidas
    {
        public int inpm_Id { get; set; }
        public int insu_Id { get; set; }
        public int unme_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime inpm_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? inpm_FechaModificacion { get; set; }


        [NotMapped]
        public string estado { get; set; }

        [NotMapped]
        public int inpp_Id { get; set; }

        [NotMapped]
        public string codigo { get; set; }
        [NotMapped]
        public string unme_Nombre { get; set; }

        [NotMapped]
        public string inpp_PrecioCompra { get; set; }

        [NotMapped]
        public string inpp_Observacion { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        public virtual tbInsumos insu { get; set; }
        public virtual tbUnidadesMedida unme { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}