// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbMaquinariasPorProveedores
    {
        public tbMaquinariasPorProveedores()
        {
            tbRentaMaquinariasPorActividades = new HashSet<tbRentaMaquinariasPorActividades>();
        }

        public int mapr_Id { get; set; }
        public decimal? mapr_PrecioCompra { get; set; }
        public int maqu_Id { get; set; }
        public int prov_Id { get; set; }
        public int usua_Creacion { get; set; }
        public int? mapr_DiaHora { get; set; }
        public DateTime mapr_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? mapr_FechaModificacion { get; set; }

        [NotMapped]
        public int nive_Id { get; set; }
        [NotMapped]
        public int codigo { get; set; }
        [NotMapped]
        public string maqu_Descripcion { get; set; }
        [NotMapped]
        public string estado { get; set; }
        [NotMapped]
        public string renta { get; set; }
        [NotMapped]
        public string nive_Descripcion { get; set; }
        [NotMapped]
        public string prov_Descripcion { get; set; }
        [NotMapped]
        public bool rmac_Recomendado { get; set; }
        [NotMapped]
        public int rmac_CantidadMaquinas { get; set; }
        [NotMapped]
        public int rmac_CantidadRenta { get; set; }
        [NotMapped]
        public decimal rmac_PrecioRenta { get; set; }

        public virtual tbMaquinarias maqu { get; set; }
        public virtual tbProveedores prov { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbRentaMaquinariasPorActividades> tbRentaMaquinariasPorActividades { get; set; }
    }
}