// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbMateriales
    {
        public tbMateriales()
        {
            tbInsumos = new HashSet<tbInsumos>();
        }

        public int mate_Id { get; set; }
        public string mate_Descripcion { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime mate_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? mate_FechaModificacion { get; set; }
        public bool? mate_Estado { get; set; }

        [NotMapped]
        public int row { get; set; }
        [NotMapped]
        public int codigo { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumos> tbInsumos { get; set; }
    }
}