// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbMaquinarias
    {
        public tbMaquinarias()
        {
            tbMaquinariasPorProveedores = new HashSet<tbMaquinariasPorProveedores>();
        }

        public int maqu_Id { get; set; }
        public string maqu_Descripcion { get; set; }
        public int nive_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime maqu_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? maqu_FechaModificacion { get; set; }
        public bool? maqu_Estado { get; set; }
        public decimal? maqu_UltimoPrecioUnitario { get; set; }

        [NotMapped]
        public string ultimoPrecio { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public string nive_Descripcion { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        public virtual tbNiveles nive { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbMaquinariasPorProveedores> tbMaquinariasPorProveedores { get; set; }
    }
}