// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbMetodosPago
    {
        public tbMetodosPago()
        {
            tbComprasEncabezado = new HashSet<tbComprasEncabezado>();
        }

        public int meto_Id { get; set; }
        public string meto_Descripcion { get; set; }
        public int meto_UsuarioCreacion { get; set; }
        public DateTime meto_FechaCreacion { get; set; }
        public int meto_UsuarioModificacion { get; set; }
        public DateTime meto_FechaModificacion { get; set; }
        public bool? meto_Estado { get; set; }

        public virtual tbUsuarios meto_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios meto_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbComprasEncabezado> tbComprasEncabezado { get; set; }
    }
}