// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbMonedas
    {
        public tbMonedas()
        {
            tbTasasCambiomone_ANavigation = new HashSet<tbTasasCambio>();
            tbTasasCambiomone_BNavigation = new HashSet<tbTasasCambio>();
        }

        public int mone_Id { get; set; }
        public string mone_Nombre { get; set; }
        public int pais_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime mone_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? mone_FechaModificacion { get; set; }
        public bool? mone_Estado { get; set; }
        public string mone_Abreviatura { get; set; }

        [NotMapped]
        public string codigo { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        [NotMapped]
        public string pais_Nombre { get; set; }


        public virtual tbPaises pais { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbTasasCambio> tbTasasCambiomone_ANavigation { get; set; }
        public virtual ICollection<tbTasasCambio> tbTasasCambiomone_BNavigation { get; set; }
    }
}