// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbNotificacionesAlertarPorUsuario
    {
        public int napu_Id { get; set; }
        public bool napu_AlertaOnoti { get; set; }
        public int napu_AlertaONotiId { get; set; }
        public int usua_Id { get; set; }
        public bool napu_Leida { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime napu_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? napu_FechaModificacion { get; set; }



        public string noti_Ruta { get; set; }
        public string noti_Descripcion { get; set; }
        public DateTime noti_Fecha { get; set; }

        public int aler_Id { get; set; }
        public string aler_Descripcion { get; set; }
        public string aler_Ruta { get; set; }
        public DateTime aler_FechaCreacion { get; set; }
        public DateTime aler_Fecha { get; set; }

        public bool? napu_Estado { get; set; }
        [NotMapped]
        public string fecha { get; set; }
        [NotMapped]
        public string leida { get; set; }
        [NotMapped]
        public int tokn_Id { get; set; }
        [NotMapped]
        public int noti_Id { get; set; }

        [NotMapped]
        public string tokn_JsonToken { get; set; }
        [NotMapped]
        public bool? tokn_SesionWeb { get; set; }

        [NotMapped]
        public string tian_Descripcion { get; set; }

        [NotMapped]
        public string descripcion { get; set; }

        [NotMapped]
        public string napu_Ruta { get; set; }
        [NotMapped]
        public string notificacionOalerta { get; set; }
        public virtual tbUsuarios usua { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}