// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbNotificaciones
    {
        public int noti_Id { get; set; }
        public string noti_Descripcion { get; set; }
        public DateTime noti_Fecha { get; set; }
        public string noti_Leida { get; set; }
        public string noti_Tipo { get; set; }
        public int usua_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime noti_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? noti_FechaModificacion { get; set; }
        public bool? noti_Estado { get; set; }


        [NotMapped]
        public int tian_Id { get; set; }
        [NotMapped]
        public string usuaNotificacion { get; set; }

        [NotMapped]
        public string tian_Descripcion { get; set; }
        [NotMapped]
        public DateTime? tian_FechaCreacion { get; set; }
        [NotMapped]
        public DateTime? tian_FechaModificacion { get; set; }


        [NotMapped]
        public string conteo { get; set; }
        [NotMapped]
        public string napu_Ruta { get; set; }

        [NotMapped]
        public string noti_Ruta { get; set; }
        [NotMapped]
        public int codigo { get; set; }
        [NotMapped]
        public string notificacionOalerta { get; set; }
        [NotMapped]
        public string descripcion { get; set; }


        [NotMapped]
        public int napu_Id { get; set; }
        [NotMapped]
        public string napu_AlertaOnoti { get; set; }
        [NotMapped]
        public string napu_AlertaONotiId { get; set; }
        [NotMapped]
        public string napu_Leida { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string napu_FechaCreacion { get; set; }
        [NotMapped]
        public string napu_Estado { get; set; }
        [NotMapped]
        public string napu_FechaModificacion { get; set; }


        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}