// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbPagos
    {
        public int pago_Id { get; set; }
        public decimal pago_Monto { get; set; }
        public DateTime pago_Fecha { get; set; }
        public int clie_Id { get; set; }
        public int proy_Id { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? pago_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? pago_FechaModificacion { get; set; }
        public bool? pago_Estado { get; set; }

        [NotMapped]
        public string cliente { get; set; }
        [NotMapped]
        public int row { get; set; }

        public virtual tbClientes clie { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}