// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbPantallasPorRoles
    {
        public int paro_Id { get; set; }
        public int pant_Id { get; set; }
        public int role_Id { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime paro_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? paro_FechaModificiacion { get; set; }
        public bool? paro_Estado { get; set; }

        [NotMapped]
        public string pant_Descripcion { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        public virtual tbPantallas pant { get; set; }
        public virtual tbRoles role { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}