// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbPaises
    {
        public tbPaises()
        {
            tbEstados = new HashSet<tbEstados>();
            tbMonedas = new HashSet<tbMonedas>();
        }

        public int pais_Id { get; set; }
        public string pais_Nombre { get; set; }
        public string pais_Codigo { get; set; }
        public string pais_Prefijo { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime pais_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? pais_FechaModificacion { get; set; }

        [NotMapped]
        public string usuarioCreacion { get; set; }
        [NotMapped]
        public string usuarioModificacion { get; set; }
        [NotMapped]
        public int codigo { get; set; }

        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstados { get; set; }
        public virtual ICollection<tbMonedas> tbMonedas { get; set; }
    }
}