// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbPlanillaDetalles
    {
        public tbPlanillaDetalles()
        {
            tbDeduccionesPorPlanilla = new HashSet<tbDeduccionesPorPlanilla>();
        }

        public int plde_Id { get; set; }
        public int plde_Frecuencia { get; set; }
        public decimal plde_SueldoBruto { get; set; }
        public decimal plde_TotalDeducciones { get; set; }
        public decimal plde_SueldoNeto { get; set; }
        public decimal plde_TotalPrestamos { get; set; }
        public int empl_Id { get; set; }
        public int plan_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime? plde_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? plde_FechaModificacion { get; set; }




        [NotMapped]
        public string dedu_Descripcion { get; set; }

        [NotMapped]
        public int dedu_Id { get; set; }

        [NotMapped]
        public int dedu_Porcentaje { get; set; }

        [NotMapped]
        public decimal empl_Salario { get; set; }

        [NotMapped]
        public decimal TotalPorDeduccion { get; set; }

        [NotMapped]
        public decimal TotalDeducido { get; set; }

        [NotMapped]
        public decimal SueldoTotal { get; set; }

        public virtual tbEmpleados empl { get; set; }
        public virtual tbPlanillas plan { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbDeduccionesPorPlanilla> tbDeduccionesPorPlanilla { get; set; }
    }
}