// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbPlanillas_Bitacora
    {
        public int plan_Id { get; set; }
        public int plan_NumNomina { get; set; }
        public DateTime? plan_FechaPago { get; set; }
        public string plan_Observaciones { get; set; }
        public bool? plan_PlanillaJefes { get; set; }
        public int? frec_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime plan_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? plan_FechaModificacion { get; set; }
        public DateTime? plan_FechaPeriodoFin { get; set; }
        public string accion { get; set; }
    }
}