// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbPlanillas
    {
        public tbPlanillas()
        {
            tbPlanillaDetalles = new HashSet<tbPlanillaDetalles>();
        }

        public int plan_Id { get; set; }
        public int plan_NumNomina { get; set; }
        public DateTime plan_FechaPago { get; set; }

        [NotMapped]
        public DateTime plan_FechaPeriodoFin { get; set; }
        public string plan_Observaciones { get; set; }
        public bool? plan_PlanillaJefes { get; set; }
        public int? frec_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime plan_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? plan_FechaModificacion { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        [NotMapped]
        public string planilla { get; set; }
        [NotMapped]
        public string frec_Descripcion { get; set; }

        public virtual tbFrecuencias frec { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPlanillaDetalles> tbPlanillaDetalles { get; set; }
    }
}