// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbPresupuestosDetalle
    {
        public int pdet_Id { get; set; }
        public int? pdet_Cantidad { get; set; }
        public decimal? pdet_PrecioManoObra { get; set; }
        public decimal? pdet_PrecioMateriales { get; set; }
        public decimal? pdet_PrecioMaquinaria { get; set; }
        public string pdet_MaquinariaFormula { get; set; }
        public string pdet_MaterialFormula { get; set; }
        public string pdet_ManoObraFormula { get; set; }
        public string pdet_CantidadFormula { get; set; }

        public int? unme_Id { get; set; }
        public int? pren_Id { get; set; }
        public int? acet_Id { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? pdet_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? pdet_FechaModificacion { get; set; }
        public bool? pdet_Incluido { get; set; }
        public decimal? pdet_Impuesto { get; set; }
        public int? pdet_Ganancia { get; set; }
        [NotMapped]
        public int copc_Id { get; set; }

        [NotMapped]
        public int etap_Id { get; set; }
        [NotMapped]
        public int etpr_Id { get; set; }
        [NotMapped]
        public string etap_Descripcion { get; set; }
        [NotMapped]
        public string acti_Descripcion { get; set; }
        [NotMapped]
        public string unme_Nombre { get; set; }

        [NotMapped]
        public string unme_Nomenclatura { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        [NotMapped]
        public int? acti_Id { get; set; }

        public virtual tbActividadesPorEtapas acet { get; set; }
        public virtual tbPresupuestosEncabezado pren { get; set; }
        public virtual tbUnidadesMedida unme { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}