// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbProyectos
    {
        public tbProyectos()
        {
            tbDocumentos = new HashSet<tbDocumentos>();
            tbEtapasPorProyectos = new HashSet<tbEtapasPorProyectos>();
            tbGestionRiesgos = new HashSet<tbGestionRiesgos>();
            tbPresupuestosEncabezado = new HashSet<tbPresupuestosEncabezado>();
            tbProyectosConstruccionBienesRaices = new HashSet<tbProyectosConstruccionBienesRaices>();
            tbRetrasos = new HashSet<tbRetrasos>();
            tbViaticosEncabezados = new HashSet<tbViaticosEncabezados>();
        }

        public int proy_Id { get; set; }
        public int tipr_Id { get; set; }
        public string proy_Nombre { get; set; }
        public string proy_Descripcion { get; set; }
        public DateTime proy_FechaInicio { get; set; }
        public DateTime proy_FechaFin { get; set; }
        public string proy_DireccionExacta { get; set; }
        public int? espr_Id { get; set; }
        public int clie_Id { get; set; }
        public int? frec_Id { get; set; }
        public int ciud_Id { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? proy_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? proy_FechaModificacion { get; set; }
        public bool? proy_Estado { get; set; }

        [NotMapped]
        public int copc_Id { get; set; }

        [NotMapped]
        public string acet_FechaInicio { get; set; }
        [NotMapped]
        public string acet_FechaFin { get; set; }
        [NotMapped]
        public string unme_Nomenclatura { get; set; }
        [NotMapped]
        public string unme_Nombre { get; set; }
        [NotMapped]
        public int unme_Id { get; set; }
        [NotMapped]
        public string acti_Descripcion { get; set; }
        [NotMapped]
        public int acti_Id { get; set; }
        [NotMapped]
        public decimal acet_PrecioManoObraFinal { get; set; }
        [NotMapped]
        public decimal acet_PrecioManoObraEstimado { get; set; }
        [NotMapped]
        public int acet_Cantidad { get; set; }
        [NotMapped]
        public int acet_Id { get; set; }
        [NotMapped]
        public string frecuencia { get; set; }
        [NotMapped]
        public int frec_NumeroDias { get; set; }
        [NotMapped]
        public int etap_Id { get; set; }
        [NotMapped]
        public string estadoPresupuesto { get; set; }

        public string proy_LinkUbicacion { get; set; }
        [NotMapped]
        public decimal? inpa_CostoInsumos { get; set; }

        [NotMapped]
        public string etap_Descripcion { get; set; }

        [NotMapped]
        public int etpr_Id { get; set; }
        public string proyecto { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public string esta_Nombre { get; set; }
        [NotMapped]
        public string pais_Nombre { get; set; }
        [NotMapped]
        public string ciud_Descripcion { get; set; }
        [NotMapped]
        public string clie_NombreCompleto { get; set; }
        [NotMapped]
        public string espr_Descripcion { get; set; }
        [NotMapped]
        public int row { get; set; }
        [NotMapped]
        public string tipr_Descripcion { get; set; }
        [NotMapped]
        public string proy_Progreso { get; set; }
        [NotMapped]
        public decimal proy_CostoInsumos { get; set; }
        [NotMapped]
        public decimal proy_CostoMaquinaria { get; set; }
        [NotMapped]
        public decimal proy_CostoEquipoSeguridad { get; set; }

        [NotMapped]
        public string icca_Imagen { get; set; }

        [NotMapped]
        public decimal proy_CostoIncidencias { get; set; }

        public virtual tbCiudades ciud { get; set; }
        public virtual tbClientes clie { get; set; }
        public virtual tbEstadosProyectos espr { get; set; }
        public virtual tbTiposProyecto tipr { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbDocumentos> tbDocumentos { get; set; }
        public virtual ICollection<tbEtapasPorProyectos> tbEtapasPorProyectos { get; set; }
        public virtual ICollection<tbGestionRiesgos> tbGestionRiesgos { get; set; }
        public virtual ICollection<tbPresupuestosEncabezado> tbPresupuestosEncabezado { get; set; }
        public virtual ICollection<tbProyectosConstruccionBienesRaices> tbProyectosConstruccionBienesRaices { get; set; }
        public virtual ICollection<tbRetrasos> tbRetrasos { get; set; }
        public virtual ICollection<tbViaticosEncabezados> tbViaticosEncabezados { get; set; }
    }
}