// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbProveedores
    {
        public tbProveedores()
        {
            tbCotizaciones = new HashSet<tbCotizaciones>();
            tbEquiposSeguridadPorProveedores = new HashSet<tbEquiposSeguridadPorProveedores>();
            tbInsumosPorProveedores = new HashSet<tbInsumosPorProveedores>();
            tbMaquinariasPorProveedores = new HashSet<tbMaquinariasPorProveedores>();
        }

        public int prov_Id { get; set; }
        public string prov_Descripcion { get; set; }
        public string prov_Correo { get; set; }
        public string prov_Telefono { get; set; }
        public string prov_SegundoTelefono { get; set; }
        public int? ciud_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime prov_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? prov_FechaModificacion { get; set; }
        public bool? prov_Estado { get; set; }
        [NotMapped]
        public int? prov_InsumoOMaquinariaOEquipoSeguridad { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string venta { get; set; }

        [NotMapped]
        public string ciud_Descripcion { get; set; }
        [NotMapped]
        public string esta_Nombre { get; set; }

        [NotMapped]
        public string pais_Nombre { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }


        public virtual tbCiudades ciud { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCotizaciones> tbCotizaciones { get; set; }
        public virtual ICollection<tbEquiposSeguridadPorProveedores> tbEquiposSeguridadPorProveedores { get; set; }
        public virtual ICollection<tbInsumosPorProveedores> tbInsumosPorProveedores { get; set; }
        public virtual ICollection<tbMaquinariasPorProveedores> tbMaquinariasPorProveedores { get; set; }
    }
}