// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbPresupuestosEncabezado
    {
        public tbPresupuestosEncabezado()
        {
            tbPresupuestosDetalle = new HashSet<tbPresupuestosDetalle>();
            tbPresupuestosPorTasasCambio = new HashSet<tbPresupuestosPorTasasCambio>();
        }

        public int pren_Id { get; set; }
        public string pren_Titulo { get; set; }
        public string pren_Descripcion { get; set; }
        public string? pren_Observacion { get; set; }
        public DateTime pren_Fecha { get; set; }
        public DateTime pren_FechaFinalizacion { get; set; }

        public string FormattedPren_Fecha => pren_Fecha.ToString("MM/dd/yyyy");
        public string FormattedPren_FechaFinalizacion => pren_FechaFinalizacion.ToString("MM/dd/yyyy");
        public string? totalPresupuesto { get; set; }
        public string? totalAjustado { get; set; }

        public decimal pren_PorcentajeGanancia { get; set; }
        public int empl_Id { get; set; }
        public int clie_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime pren_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? pren_FechaModificacion { get; set; }

        public int? proy_Id { get; set; }


        [NotMapped]
        public string cliente { get; set; }

        [NotMapped]
        public string empleado { get; set; }
        [NotMapped]
        public int codigo { get; set; }
        [NotMapped]
        public string empl_DNI { get; set; }
        [NotMapped]
        public string clie_DNI { get; set; }
        [NotMapped]
        public string proyecto { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        public string? pren_Estado { get; set; }

        public bool pren_Maquinaria { get; set; }
        public decimal? pren_Impuesto { get; set; }
        public virtual tbClientes clie { get; set; }
        public virtual tbEmpleados empl { get; set; }
        public virtual tbProyectos proy { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPresupuestosDetalle> tbPresupuestosDetalle { get; set; }
        public virtual ICollection<tbPresupuestosPorTasasCambio> tbPresupuestosPorTasasCambio { get; set; }
    }
}