// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbProyectosConstruccionBienesRaices
    {
        public tbProyectosConstruccionBienesRaices()
        {
            tbBienesRaices = new HashSet<tbBienesRaices>();
        }

        public int pcon_Id { get; set; }
        public int terr_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime pcon_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? pcon_FechaModificacion { get; set; }
        public bool? pcon_Estado { get; set; }
        public int proy_Id { get; set; }


        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        [NotMapped]
        public string proy_Descripcion { get; set; }

        [NotMapped]
        public string proy_DireccionExacta { get; set; }
        [NotMapped]
        public string terr_Descripcion { get; set; }
        [NotMapped]
        public string terr_Direccion { get; set; }

        [NotMapped]
        public double precio { get; set; }

        public virtual tbProyectos proy { get; set; }
        public virtual tbTerrenos terr { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbBienesRaices> tbBienesRaices { get; set; }
    }
}