// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbPresupuestosPorTasasCambio
    {
        public int pptc_Id { get; set; }
        public int? pren_Id { get; set; }
        public int? taca_Id { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? pptc_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? pptc_FechaModificacion { get; set; }


        [NotMapped]
        public int moneId_A { get; set; }
        [NotMapped]
        public int moneId_B { get; set; }
        [NotMapped]
        public string nombreMone_A { get; set; }
        [NotMapped]
        public string moneAbreviaturaA { get; set; }
        [NotMapped]
        public string moneAbreviaturaB { get; set; }
        [NotMapped]
        public string taca_ValorA { get; set; }
        [NotMapped]
        public string nombreMone_B { get; set; }
        [NotMapped]
        public string taca_ValorB { get; set; }

        public virtual tbPresupuestosEncabezado pren { get; set; }
        public virtual tbTasasCambio taca { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}