// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbPrestamos_Bitacora
    {
        public int pres_Id { get; set; }
        public decimal pres_Monto { get; set; }
        public string pres_Descripcion { get; set; }
        public DateTime pres_FechaPrimerPago { get; set; }
        public int pres_Pagos { get; set; }
        public int? empl_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime pres_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? pres_FechaModificacion { get; set; }
        public bool? pres_Estado { get; set; }
        public int? frec_Id { get; set; }
        public int? pres_PagosRestantes { get; set; }
        public string pres_UltimaFechaPago { get; set; }
        public decimal? pres_TasaInteres { get; set; }
        public string accion { get; set; }
    }
}