// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbRentaMaquinariasPorActividades
    {
        public int rmac_Id { get; set; }
        public DateTime? rmac_FechaContratacion { get; set; }
        public int? rmac_Rentapor { get; set; }
        public int? rmac_CantidadRenta { get; set; }
        public decimal? rmac_PrecioRenta { get; set; }
        public int? rmac_CantidadMaquinas { get; set; }
        public int? mapr_Id { get; set; }
        public int? acet_Id { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime rmac_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? rmac_FechaModificacion { get; set; }
        public string? rmac_CantidadMaquinaFormula { get; set; }
        public string? rmac_PrecioRentaFormula { get; set; }
        public string? rmac_CantidadRentaFormula { get; set; }
        public int? rmac_ActividadLlenado { get; set; }


        public bool rmac_Estado { get; set; }
        [NotMapped]
        public string renta { get; set; }
        [NotMapped]
        public string nive_Id { get; set; }
        [NotMapped]
        public string nive_Descripcion { get; set; }
        [NotMapped]
        public string prov_Id { get; set; }
        [NotMapped]
        public string prov_Descripcion { get; set; }
        [NotMapped]
        public string maqu_Id { get; set; }
        [NotMapped]
        public string maqu_Descripcion { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }


        public int rmac_HorasRenta { get; set; }

        public virtual tbActividadesPorEtapas acet { get; set; }
        public virtual tbMaquinariasPorProveedores mapr { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}