// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbRetrasos
    {
        public int retr_Id { get; set; }
        public string retr_Descripcion { get; set; }
        public decimal retr_Monto { get; set; }
        public DateTime retr_Fecha { get; set; }
        public int? Proy_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime retr_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? retr_FechaModificacion { get; set; }
        public bool? retr_Estado { get; set; }

        public virtual tbProyectos Proy { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
    }
}