// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbSubcategorias
    {
        public tbSubcategorias()
        {
            tbInsumos = new HashSet<tbInsumos>();
        }

        public int suca_Id { get; set; }
        public string suca_Descripcion { get; set; }
        public int cate_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime suca_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? suca_FechaModificacion { get; set; }
        public bool? suca_Estado { get; set; }

        [NotMapped]
        public string cate_Descripcion { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }

        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public int codigo { get; set; }


        public virtual tbCategorias cate { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumos> tbInsumos { get; set; }
    }
}