// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbTasasCambio
    {
        public tbTasasCambio()
        {
            tbPresupuestosPorTasasCambio = new HashSet<tbPresupuestosPorTasasCambio>();
        }

        public int taca_Id { get; set; }
        public int mone_A { get; set; }
        public decimal? taca_ValorA { get; set; }
        public int mone_B { get; set; }
        public decimal taca_ValorB { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime taca_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? taca_FechaModificacion { get; set; }
        public bool? taca_Estado { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public int codigo { get; set; }
        [NotMapped]
        public int moneId_A { get; set; }
        [NotMapped]
        public int moneId_B { get; set; }

        [NotMapped]
        public string nombreMone_A { get; set; }
        [NotMapped]
        public string moneAbreviaturaA { get; set; }
        [NotMapped]
        public string nombreMone_B { get; set; }
        [NotMapped]
        public string moneAbreviaturaB { get; set; }

        [NotMapped]
        public string moneda_A { get; set; }
        [NotMapped]
        public string moneda_B { get; set; }

        public virtual tbMonedas mone_ANavigation { get; set; }
        public virtual tbMonedas mone_BNavigation { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPresupuestosPorTasasCambio> tbPresupuestosPorTasasCambio { get; set; }
    }
}