// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbTerrenos
    {
        public tbTerrenos()
        {
            tbProyectosConstruccionBienesRaices = new HashSet<tbProyectosConstruccionBienesRaices>();
        }

        public int terr_Id { get; set; }
        public string terr_Descripcion { get; set; }
        public string terr_Area { get; set; }
        public bool? terr_Estado { get; set; }
        public string terr_PecioCompra { get; set; }
        public string terr_PrecioVenta { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime terr_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? terr_FechaModificacion { get; set; }
        public string terr_LinkUbicacion { get; set; }
        public string terr_Imagen { get; set; }
        public string terr_Latitud { get; set; }
        public string terr_Longitud { get; set; }
        public bool? terr_Identificador { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public string descripcion { get; set; }
        [NotMapped]
        public int DocumentoId { get; set; }
        [NotMapped]
        public string DescripcionDocumento { get; set; }
        [NotMapped]
        public DateTime? DocumentoFechaCreacion { get; set; }
        [NotMapped]
        public int TipoDocumentoId { get; set; }
        [NotMapped]
        public string TipoDocumentoDescripcion { get; set; }
        [NotMapped]
        public int Codigo { get; set; }
        [NotMapped]
        public string DocumentoImagen { get; set; }

        [NotMapped]
        public int Codigo2 { get; set; }
        [NotMapped]
        public string dobt_DescipcionDocumento { get; set; }

        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbProyectosConstruccionBienesRaices> tbProyectosConstruccionBienesRaices { get; set; }
    }
}