// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbTiposDocumentos
    {
        public tbTiposDocumentos()
        {
            tbDocumentosBienRaiz = new HashSet<tbDocumentosBienRaiz>();
        }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public string codigo { get; set; }


        public int tido_Id { get; set; }
        public string tido_Descripcion { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime tido_FechaCreacion { get; set; }
        public int? usua_Mofificacion { get; set; }
        public DateTime? tido_FechaModificacion { get; set; }
        public bool? tido_Estado { get; set; }

        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_MofificacionNavigation { get; set; }
        public virtual ICollection<tbDocumentosBienRaiz> tbDocumentosBienRaiz { get; set; }
    }
}