// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbTokens
    {
        public int tokn_Id { get; set; }
        public int usua_Id { get; set; }
        public string tokn_JsonToken { get; set; }
        public bool? tokn_SesionWeb { get; set; }

        public virtual tbUsuarios usua { get; set; }
    }
}