// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbUnidadesMedida
    {
        public tbUnidadesMedida()
        {
            tbActividadesPorEtapas = new HashSet<tbActividadesPorEtapas>();
            tbCostoPorActividad = new HashSet<tbCostoPorActividad>();
            tbInsumosPorMedidas = new HashSet<tbInsumosPorMedidas>();
            tbPresupuestosDetalle = new HashSet<tbPresupuestosDetalle>();
        }

        public int unme_Id { get; set; }
        public string unme_Nombre { get; set; }
        public string unme_Nomenclatura { get; set; }
        public int? usua_Creacion { get; set; }
        public DateTime? unme_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? unme_FechaModificacion { get; set; }
        public bool? unme_Estado { get; set; }

        [NotMapped]
        public int codigo { get; set; }

        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public string usuaCreacion { get; set; }

        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbActividadesPorEtapas> tbActividadesPorEtapas { get; set; }
        public virtual ICollection<tbCostoPorActividad> tbCostoPorActividad { get; set; }
        public virtual ICollection<tbInsumosPorMedidas> tbInsumosPorMedidas { get; set; }
        public virtual ICollection<tbPresupuestosDetalle> tbPresupuestosDetalle { get; set; }
    }
}