// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusua_CreacionNavigation = new HashSet<tbUsuarios>();
            Inverseusua_ModificacionNavigation = new HashSet<tbUsuarios>();
            tbAbonosPorPrestamosusua_CreacionNavigation = new HashSet<tbAbonosPorPrestamos>();
            tbAbonosPorPrestamosusua_ModificacionNavigation = new HashSet<tbAbonosPorPrestamos>();
            tbActividadesPorEtapasusua_CreacionNavigation = new HashSet<tbActividadesPorEtapas>();
            tbActividadesPorEtapasusua_ModificacionNavigation = new HashSet<tbActividadesPorEtapas>();
            tbActividadesusua_CreacionNavigation = new HashSet<tbActividades>();
            tbActividadesusua_ModificacionNavigation = new HashSet<tbActividades>();
            tbAgentesBienesRaicesusua_CreacionNavigation = new HashSet<tbAgentesBienesRaices>();
            tbAgentesBienesRaicesusua_ModificacionNavigation = new HashSet<tbAgentesBienesRaices>();
            tbAlertasusua_CreacionNavigation = new HashSet<tbAlertas>();
            tbAlertasusua_ModificacionNavigation = new HashSet<tbAlertas>();
            tbBancosusua_CreacionNavigation = new HashSet<tbBancos>();
            tbBancosusua_ModificacionNavigation = new HashSet<tbBancos>();
            tbBienesRaicesusua_CreacionNavigation = new HashSet<tbBienesRaices>();
            tbBienesRaicesusua_ModificacionNavigation = new HashSet<tbBienesRaices>();
            tbBodegasPorInsumousua_CreacionNavigation = new HashSet<tbBodegasPorInsumo>();
            tbBodegasPorInsumousua_ModificacionNavigation = new HashSet<tbBodegasPorInsumo>();
            tbBodegasusua_CreacionNavigation = new HashSet<tbBodegas>();
            tbBodegasusua_ModificacionNavigation = new HashSet<tbBodegas>();
            tbCargosusua_CreacionNavigation = new HashSet<tbCargos>();
            tbCargosusua_ModificacionNavigation = new HashSet<tbCargos>();
            tbCategoriasViaticosusua_CreacionNavigation = new HashSet<tbCategoriasViaticos>();
            tbCategoriasViaticosusua_ModificacionNavigation = new HashSet<tbCategoriasViaticos>();
            tbCategoriasusua_CreacionNavigation = new HashSet<tbCategorias>();
            tbCategoriasusua_ModificacionNavigation = new HashSet<tbCategorias>();
            tbCiudadesusua_CreacionNavigation = new HashSet<tbCiudades>();
            tbCiudadesusua_ModificacionNavigation = new HashSet<tbCiudades>();
            tbClientesusua_CreacionNavigation = new HashSet<tbClientes>();
            tbClientesusua_ModificacionNavigation = new HashSet<tbClientes>();
            tbComprasDetallesDireccionesPorMaquinariausua_CreacionNavigation = new HashSet<tbComprasDetallesDireccionesPorMaquinaria>();
            tbComprasDetallesDireccionesPorMaquinariausua_ModficacionNavigation = new HashSet<tbComprasDetallesDireccionesPorMaquinaria>();
            tbComprasDetallesDireccionesusua_CreacionNavigation = new HashSet<tbComprasDetallesDirecciones>();
            tbComprasDetallesDireccionesusua_ModificacionNavigation = new HashSet<tbComprasDetallesDirecciones>();
            tbComprasDetalleusua_CreacionNavigation = new HashSet<tbComprasDetalle>();
            tbComprasDetalleusua_ModificacionNavigation = new HashSet<tbComprasDetalle>();
            tbComprasEncabezadousua_CreacionNavigation = new HashSet<tbComprasEncabezado>();
            tbComprasEncabezadousua_ModificacionNavigation = new HashSet<tbComprasEncabezado>();
            tbControlDeCalidadesPorActividadesusua_CreacionNavigation = new HashSet<tbControlDeCalidadesPorActividades>();
            tbControlDeCalidadesPorActividadesusua_ModificacionNavigation = new HashSet<tbControlDeCalidadesPorActividades>();
            tbCostoPorActividadusua_CreacionNavigation = new HashSet<tbCostoPorActividad>();
            tbCostoPorActividadusua_ModificacionNavigation = new HashSet<tbCostoPorActividad>();
            tbCotizacionesDetalleusua_CreacionNavigation = new HashSet<tbCotizacionesDetalle>();
            tbCotizacionesDetalleusua_ModificacionNavigation = new HashSet<tbCotizacionesDetalle>();
            tbCotizacionesPorDocumentosusua_CreacionNavigation = new HashSet<tbCotizacionesPorDocumentos>();
            tbCotizacionesPorDocumentosusua_ModificacionNavigation = new HashSet<tbCotizacionesPorDocumentos>();
            tbCotizacionesusua_CreacionNavigation = new HashSet<tbCotizaciones>();
            tbCotizacionesusua_ModificacionNavigation = new HashSet<tbCotizaciones>();
            tbDeduccionesPorEmpleadosusua_CreacionNavigation = new HashSet<tbDeduccionesPorEmpleados>();
            tbDeduccionesPorEmpleadosusua_ModificacionNavigation = new HashSet<tbDeduccionesPorEmpleados>();
            tbDeduccionesPorPlanillausua_CreacionNavigation = new HashSet<tbDeduccionesPorPlanilla>();
            tbDeduccionesPorPlanillausua_ModificacionNavigation = new HashSet<tbDeduccionesPorPlanilla>();
            tbDeduccionesusua_CreacionNavigation = new HashSet<tbDeducciones>();
            tbDeduccionesusua_ModificacionNavigation = new HashSet<tbDeducciones>();
            tbDocumentosBienRaizusua_CreacionNavigation = new HashSet<tbDocumentosBienRaiz>();
            tbDocumentosBienRaizusua_ModificacionNavigation = new HashSet<tbDocumentosBienRaiz>();
            tbDocumentosusua_CreacionNavigation = new HashSet<tbDocumentos>();
            tbDocumentosusua_ModificacionNavigation = new HashSet<tbDocumentos>();
            tbEmpleados = new HashSet<tbEmpleados>();
            tbEmpresasBienesRaicesusua_CreacionNavigation = new HashSet<tbEmpresasBienesRaices>();
            tbEmpresasBienesRaicesusua_ModificacionNavigation = new HashSet<tbEmpresasBienesRaices>();
            tbEquiposSeguridadPorActividadesusua_CreacionNavigation = new HashSet<tbEquiposSeguridadPorActividades>();
            tbEquiposSeguridadPorActividadesusua_ModificacionNavigation = new HashSet<tbEquiposSeguridadPorActividades>();
            tbEquiposSeguridadPorBodegasusua_CreacionNavigation = new HashSet<tbEquiposSeguridadPorBodegas>();
            tbEquiposSeguridadPorBodegasusua_ModificacionNavigation = new HashSet<tbEquiposSeguridadPorBodegas>();
            tbEquiposSeguridadPorProveedoresusua_CreacionNavigation = new HashSet<tbEquiposSeguridadPorProveedores>();
            tbEquiposSeguridadPorProveedoresusua_ModificacionNavigation = new HashSet<tbEquiposSeguridadPorProveedores>();
            tbEquiposSeguridadusua_CreacionNavigation = new HashSet<tbEquiposSeguridad>();
            tbEquiposSeguridadusua_ModificacionNavigation = new HashSet<tbEquiposSeguridad>();
            tbEstadosCivilesusua_CreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesusua_ModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosProyectosusua_CreacionNavigation = new HashSet<tbEstadosProyectos>();
            tbEstadosProyectosusua_ModificacionNavigation = new HashSet<tbEstadosProyectos>();
            tbEstadosusua_CreacionNavigation = new HashSet<tbEstados>();
            tbEstadosusua_ModificacionNavigation = new HashSet<tbEstados>();
            tbEtapasPorProyectosusua_CreacionNavigation = new HashSet<tbEtapasPorProyectos>();
            tbEtapasPorProyectosusua_ModificacionNavigation = new HashSet<tbEtapasPorProyectos>();
            tbEtapasusua_CreacionNavigation = new HashSet<tbEtapas>();
            tbEtapasusua_ModificacionNavigation = new HashSet<tbEtapas>();
            tbFletesControlCalidadusua_CreacionNavigation = new HashSet<tbFletesControlCalidad>();
            tbFletesControlCalidadusua_ModificacionNavigation = new HashSet<tbFletesControlCalidad>();
            tbFletesDetalleusua_CreacionNavigation = new HashSet<tbFletesDetalle>();
            tbFletesDetalleusua_ModificacionNavigation = new HashSet<tbFletesDetalle>();
            tbFletesEncabezadousua_CreacionNavigation = new HashSet<tbFletesEncabezado>();
            tbFletesEncabezadousua_ModificacionNavigation = new HashSet<tbFletesEncabezado>();
            tbFrecuenciasusua_CreacionNavigation = new HashSet<tbFrecuencias>();
            tbFrecuenciasusua_ModificacionNavigation = new HashSet<tbFrecuencias>();
            tbGestionRiesgosusua_CreacionNavigation = new HashSet<tbGestionRiesgos>();
            tbGestionRiesgosusua_ModificacionNavigation = new HashSet<tbGestionRiesgos>();
            tbGestionesAdicionalesusua_CreacionNavigation = new HashSet<tbGestionesAdicionales>();
            tbGestionesAdicionalesusua_ModificacionNavigation = new HashSet<tbGestionesAdicionales>();
            tbImagenesPorControlesDeCalidadesusua_CreacionNavigation = new HashSet<tbImagenesPorControlesDeCalidades>();
            tbImagenesPorControlesDeCalidadesusua_ModificacionNavigation = new HashSet<tbImagenesPorControlesDeCalidades>();
            tbImagenesPorGestionesAdicionalesusua_CreacionNavigation = new HashSet<tbImagenesPorGestionesAdicionales>();
            tbImagenesPorGestionesAdicionalesusua_ModificacionNavigation = new HashSet<tbImagenesPorGestionesAdicionales>();
            tbImagenesPorIncidenciasusua_CreacionNavigation = new HashSet<tbImagenesPorIncidencias>();
            tbImagenesPorIncidenciasusua_ModificacionNavigation = new HashSet<tbImagenesPorIncidencias>();
            tbImagenesPorProcesosVentasusua_CreacionNavigation = new HashSet<tbImagenesPorProcesosVentas>();
            tbImagenesPorProcesosVentasusua_ModificacionNavigation = new HashSet<tbImagenesPorProcesosVentas>();
            tbImpuestosusua_CreacionNavigation = new HashSet<tbImpuestos>();
            tbImpuestosusua_ModificacionNavigation = new HashSet<tbImpuestos>();
            tbIncidenciasPorActividadesusua_CreacionNavigation = new HashSet<tbIncidenciasPorActividades>();
            tbIncidenciasPorActividadesusua_ModificacionNavigation = new HashSet<tbIncidenciasPorActividades>();
            tbIncidenciasPorFletesusua_CreacionNavigation = new HashSet<tbIncidenciasPorFletes>();
            tbIncidenciasPorFletesusua_ModificacionNavigation = new HashSet<tbIncidenciasPorFletes>();
            tbIncidentesusua_CreacionNavigation = new HashSet<tbIncidentes>();
            tbIncidentesusua_ModificacionNavigation = new HashSet<tbIncidentes>();
            tbInsumosPorActividadesusua_CreacionNavigation = new HashSet<tbInsumosPorActividades>();
            tbInsumosPorActividadesusua_ModificacionNavigation = new HashSet<tbInsumosPorActividades>();
            tbInsumosPorMedidasusua_CreacionNavigation = new HashSet<tbInsumosPorMedidas>();
            tbInsumosPorMedidasusua_ModificacionNavigation = new HashSet<tbInsumosPorMedidas>();
            tbInsumosPorProveedoresusua_CreacionNavigation = new HashSet<tbInsumosPorProveedores>();
            tbInsumosPorProveedoresusua_ModificacionNavigation = new HashSet<tbInsumosPorProveedores>();
            tbInsumosusua_CreacionNavigation = new HashSet<tbInsumos>();
            tbInsumosusua_ModificacionNavigation = new HashSet<tbInsumos>();
            tbMantenimientosusua_CreacionNavigation = new HashSet<tbMantenimientos>();
            tbMantenimientosusua_ModificacionNavigation = new HashSet<tbMantenimientos>();
            tbMaquinariasPorProveedoresusua_CreacionNavigation = new HashSet<tbMaquinariasPorProveedores>();
            tbMaquinariasPorProveedoresusua_ModificacionNavigation = new HashSet<tbMaquinariasPorProveedores>();
            tbMaquinariasusua_CreacionNavigation = new HashSet<tbMaquinarias>();
            tbMaquinariasusua_ModificacionNavigation = new HashSet<tbMaquinarias>();
            tbMaterialesusua_CreacionNavigation = new HashSet<tbMateriales>();
            tbMaterialesusua_ModificacionNavigation = new HashSet<tbMateriales>();
            tbMetodosPagometo_UsuarioCreacionNavigation = new HashSet<tbMetodosPago>();
            tbMetodosPagometo_UsuarioModificacionNavigation = new HashSet<tbMetodosPago>();
            tbMonedasusua_CreacionNavigation = new HashSet<tbMonedas>();
            tbMonedasusua_ModificacionNavigation = new HashSet<tbMonedas>();
            tbNivelesusua_CreacionNavigation = new HashSet<tbNiveles>();
            tbNivelesusua_ModificacionNavigation = new HashSet<tbNiveles>();
            tbNotificacionesAlertarPorUsuariousua = new HashSet<tbNotificacionesAlertarPorUsuario>();
            tbNotificacionesAlertarPorUsuariousua_CreacionNavigation = new HashSet<tbNotificacionesAlertarPorUsuario>();
            tbNotificacionesAlertarPorUsuariousua_ModificacionNavigation = new HashSet<tbNotificacionesAlertarPorUsuario>();
            tbNotificacionesusua_CreacionNavigation = new HashSet<tbNotificaciones>();
            tbNotificacionesusua_ModificacionNavigation = new HashSet<tbNotificaciones>();
            tbPagosusua_CreacionNavigation = new HashSet<tbPagos>();
            tbPagosusua_ModificacionNavigation = new HashSet<tbPagos>();
            tbPaisesusua_CreacionNavigation = new HashSet<tbPaises>();
            tbPaisesusua_ModificacionNavigation = new HashSet<tbPaises>();
            tbPantallasPorRolesusua_CreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesusua_ModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasusua_CreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasusua_ModificacionNavigation = new HashSet<tbPantallas>();
            tbPlanillaDetallesusua_CreacionNavigation = new HashSet<tbPlanillaDetalles>();
            tbPlanillaDetallesusua_ModificacionNavigation = new HashSet<tbPlanillaDetalles>();
            tbPlanillasusua_CreacionNavigation = new HashSet<tbPlanillas>();
            tbPlanillasusua_ModificacionNavigation = new HashSet<tbPlanillas>();
            tbPrestamosusua_CreacionNavigation = new HashSet<tbPrestamos>();
            tbPrestamosusua_ModificacionNavigation = new HashSet<tbPrestamos>();
            tbPresupuestosDetalleusua_CreacionNavigation = new HashSet<tbPresupuestosDetalle>();
            tbPresupuestosDetalleusua_ModificacionNavigation = new HashSet<tbPresupuestosDetalle>();
            tbPresupuestosEncabezadousua_CreacionNavigation = new HashSet<tbPresupuestosEncabezado>();
            tbPresupuestosEncabezadousua_ModificacionNavigation = new HashSet<tbPresupuestosEncabezado>();
            tbPresupuestosPorTasasCambiousua_CreacionNavigation = new HashSet<tbPresupuestosPorTasasCambio>();
            tbPresupuestosPorTasasCambiousua_ModificacionNavigation = new HashSet<tbPresupuestosPorTasasCambio>();
            tbProcesosVentasusua_CreacionNavigation = new HashSet<tbProcesosVentas>();
            tbProcesosVentasusua_ModificacionNavigation = new HashSet<tbProcesosVentas>();
            tbProveedoresusua_CreacionNavigation = new HashSet<tbProveedores>();
            tbProveedoresusua_ModificacionNavigation = new HashSet<tbProveedores>();
            tbProyectosConstruccionBienesRaicesusua_CreacionNavigation = new HashSet<tbProyectosConstruccionBienesRaices>();
            tbProyectosConstruccionBienesRaicesusua_ModificacionNavigation = new HashSet<tbProyectosConstruccionBienesRaices>();
            tbProyectosusua_CreacionNavigation = new HashSet<tbProyectos>();
            tbProyectosusua_ModificacionNavigation = new HashSet<tbProyectos>();
            tbReferenciasCeldasusua_CreacionNavigation = new HashSet<tbReferenciasCeldas>();
            tbReferenciasCeldasusua_ModificacionNavigation = new HashSet<tbReferenciasCeldas>();
            tbRentaMaquinariasPorActividadesusua_CreacionNavigation = new HashSet<tbRentaMaquinariasPorActividades>();
            tbRentaMaquinariasPorActividadesusua_ModificacionNavigation = new HashSet<tbRentaMaquinariasPorActividades>();
            tbRetrasosusua_CreacionNavigation = new HashSet<tbRetrasos>();
            tbRetrasosusua_ModificacionNavigation = new HashSet<tbRetrasos>();
            tbRolesusua_CreacionNavigation = new HashSet<tbRoles>();
            tbRolesusua_ModificacionNavigation = new HashSet<tbRoles>();
            tbSubcategoriasusua_CreacionNavigation = new HashSet<tbSubcategorias>();
            tbSubcategoriasusua_ModificacionNavigation = new HashSet<tbSubcategorias>();
            tbTasasCambiousua_CreacionNavigation = new HashSet<tbTasasCambio>();
            tbTasasCambiousua_ModificacionNavigation = new HashSet<tbTasasCambio>();
            tbTerrenosusua_CreacionNavigation = new HashSet<tbTerrenos>();
            tbTerrenosusua_ModificacionNavigation = new HashSet<tbTerrenos>();
            tbTiposDocumentosusua_CreacionNavigation = new HashSet<tbTiposDocumentos>();
            tbTiposDocumentosusua_MofificacionNavigation = new HashSet<tbTiposDocumentos>();
            tbTiposProyectousua_CreacionNavigation = new HashSet<tbTiposProyecto>();
            tbTiposProyectousua_ModificacionNavigation = new HashSet<tbTiposProyecto>();
            tbTokens = new HashSet<tbTokens>();
            tbUnidadesMedidausua_CreacionNavigation = new HashSet<tbUnidadesMedida>();
            tbUnidadesMedidausua_ModificacionNavigation = new HashSet<tbUnidadesMedida>();
            tbViaticosDetallesusua_CreacionNavigation = new HashSet<tbViaticosDetalles>();
            tbViaticosDetallesusua_ModificacionNavigation = new HashSet<tbViaticosDetalles>();
            tbViaticosEncabezadosusua_CreacionNavigation = new HashSet<tbViaticosEncabezados>();
            tbViaticosEncabezadosusua_ModificacionNavigation = new HashSet<tbViaticosEncabezados>();
        }

        public int usua_Id { get; set; }
        public string usua_Usuario { get; set; }
        public string usua_Clave { get; set; }
        public bool usua_EsAdministrador { get; set; }
        public int? empl_Id { get; set; }
        public int role_Id { get; set; }
        public int? usua_Creacion { get; set; }

        public string usua_ObservacionInactivar { get; set; }


        public DateTime? usua_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }
        public bool? usua_Estado { get; set; }
        [NotMapped]
        public string empleadoSinDNI { get; set; }
        [NotMapped]
        public string empleadoDNI { get; set; }
        [NotMapped]
        public string role_Descripcion { get; set; }
        [NotMapped]
        public string empleado { get; set; }

        [NotMapped]
        public string codigo { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }
        [NotMapped]
        public string nombre_Empleado { get; set; }
        [NotMapped]
        public string empl_CorreoElectronico { get; set; }
        [NotMapped]
        public string empl_Telefono { get; set; }
        [NotMapped]
        public string empl_Imagen { get; set; }
        [NotMapped]
        public string carg_Descripcion { get; set; }

        [NotMapped]
        public DateTime empl_FechaNacimiento { get; set; }

        public virtual tbEmpleados empl { get; set; }
        public virtual tbRoles role { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbAbonosPorPrestamos> tbAbonosPorPrestamosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbAbonosPorPrestamos> tbAbonosPorPrestamosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbActividadesPorEtapas> tbActividadesPorEtapasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbActividadesPorEtapas> tbActividadesPorEtapasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbActividades> tbActividadesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbActividades> tbActividadesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbAgentesBienesRaices> tbAgentesBienesRaicesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbAgentesBienesRaices> tbAgentesBienesRaicesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbAlertas> tbAlertasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbAlertas> tbAlertasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbBancos> tbBancosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbBancos> tbBancosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbBienesRaices> tbBienesRaicesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbBienesRaices> tbBienesRaicesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbBodegasPorInsumo> tbBodegasPorInsumousua_CreacionNavigation { get; set; }
        public virtual ICollection<tbBodegasPorInsumo> tbBodegasPorInsumousua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbBodegas> tbBodegasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbBodegas> tbBodegasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCategoriasViaticos> tbCategoriasViaticosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbCategoriasViaticos> tbCategoriasViaticosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudadesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbCiudades> tbCiudadesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbComprasDetallesDireccionesPorMaquinaria> tbComprasDetallesDireccionesPorMaquinariausua_CreacionNavigation { get; set; }
        public virtual ICollection<tbComprasDetallesDireccionesPorMaquinaria> tbComprasDetallesDireccionesPorMaquinariausua_ModficacionNavigation { get; set; }
        public virtual ICollection<tbComprasDetallesDirecciones> tbComprasDetallesDireccionesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbComprasDetallesDirecciones> tbComprasDetallesDireccionesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbComprasDetalle> tbComprasDetalleusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbComprasDetalle> tbComprasDetalleusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbComprasEncabezado> tbComprasEncabezadousua_CreacionNavigation { get; set; }
        public virtual ICollection<tbComprasEncabezado> tbComprasEncabezadousua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbControlDeCalidadesPorActividades> tbControlDeCalidadesPorActividadesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbControlDeCalidadesPorActividades> tbControlDeCalidadesPorActividadesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCostoPorActividad> tbCostoPorActividadusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbCostoPorActividad> tbCostoPorActividadusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCotizacionesDetalle> tbCotizacionesDetalleusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbCotizacionesDetalle> tbCotizacionesDetalleusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCotizacionesPorDocumentos> tbCotizacionesPorDocumentosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbCotizacionesPorDocumentos> tbCotizacionesPorDocumentosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbCotizaciones> tbCotizacionesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbCotizaciones> tbCotizacionesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbDeduccionesPorEmpleados> tbDeduccionesPorEmpleadosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbDeduccionesPorEmpleados> tbDeduccionesPorEmpleadosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbDeduccionesPorPlanilla> tbDeduccionesPorPlanillausua_CreacionNavigation { get; set; }
        public virtual ICollection<tbDeduccionesPorPlanilla> tbDeduccionesPorPlanillausua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbDeducciones> tbDeduccionesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbDeducciones> tbDeduccionesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbDocumentosBienRaiz> tbDocumentosBienRaizusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbDocumentosBienRaiz> tbDocumentosBienRaizusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbDocumentos> tbDocumentosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbDocumentos> tbDocumentosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbEmpresasBienesRaices> tbEmpresasBienesRaicesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEmpresasBienesRaices> tbEmpresasBienesRaicesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEquiposSeguridadPorActividades> tbEquiposSeguridadPorActividadesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEquiposSeguridadPorActividades> tbEquiposSeguridadPorActividadesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEquiposSeguridadPorBodegas> tbEquiposSeguridadPorBodegasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEquiposSeguridadPorBodegas> tbEquiposSeguridadPorBodegasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEquiposSeguridadPorProveedores> tbEquiposSeguridadPorProveedoresusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEquiposSeguridadPorProveedores> tbEquiposSeguridadPorProveedoresusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEquiposSeguridad> tbEquiposSeguridadusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEquiposSeguridad> tbEquiposSeguridadusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosProyectos> tbEstadosProyectosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosProyectos> tbEstadosProyectosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEtapasPorProyectos> tbEtapasPorProyectosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEtapasPorProyectos> tbEtapasPorProyectosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEtapas> tbEtapasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEtapas> tbEtapasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbFletesControlCalidad> tbFletesControlCalidadusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbFletesControlCalidad> tbFletesControlCalidadusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbFletesDetalle> tbFletesDetalleusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbFletesDetalle> tbFletesDetalleusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbFletesEncabezado> tbFletesEncabezadousua_CreacionNavigation { get; set; }
        public virtual ICollection<tbFletesEncabezado> tbFletesEncabezadousua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbFrecuencias> tbFrecuenciasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbFrecuencias> tbFrecuenciasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbGestionRiesgos> tbGestionRiesgosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbGestionRiesgos> tbGestionRiesgosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbGestionesAdicionales> tbGestionesAdicionalesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbGestionesAdicionales> tbGestionesAdicionalesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbImagenesPorControlesDeCalidades> tbImagenesPorControlesDeCalidadesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbImagenesPorControlesDeCalidades> tbImagenesPorControlesDeCalidadesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbImagenesPorGestionesAdicionales> tbImagenesPorGestionesAdicionalesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbImagenesPorGestionesAdicionales> tbImagenesPorGestionesAdicionalesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbImagenesPorIncidencias> tbImagenesPorIncidenciasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbImagenesPorIncidencias> tbImagenesPorIncidenciasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbImagenesPorProcesosVentas> tbImagenesPorProcesosVentasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbImagenesPorProcesosVentas> tbImagenesPorProcesosVentasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbImpuestos> tbImpuestosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbImpuestos> tbImpuestosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbIncidenciasPorActividades> tbIncidenciasPorActividadesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbIncidenciasPorActividades> tbIncidenciasPorActividadesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbIncidenciasPorFletes> tbIncidenciasPorFletesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbIncidenciasPorFletes> tbIncidenciasPorFletesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbIncidentes> tbIncidentesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbIncidentes> tbIncidentesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumosPorActividades> tbInsumosPorActividadesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbInsumosPorActividades> tbInsumosPorActividadesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumosPorMedidas> tbInsumosPorMedidasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbInsumosPorMedidas> tbInsumosPorMedidasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumosPorProveedores> tbInsumosPorProveedoresusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbInsumosPorProveedores> tbInsumosPorProveedoresusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumos> tbInsumosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbInsumos> tbInsumosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbMantenimientos> tbMantenimientosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbMantenimientos> tbMantenimientosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbMaquinariasPorProveedores> tbMaquinariasPorProveedoresusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbMaquinariasPorProveedores> tbMaquinariasPorProveedoresusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbMaquinarias> tbMaquinariasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbMaquinarias> tbMaquinariasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbMateriales> tbMaterialesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbMateriales> tbMaterialesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagometo_UsuarioCreacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagometo_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMonedas> tbMonedasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbMonedas> tbMonedasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbNiveles> tbNivelesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbNiveles> tbNivelesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbNotificacionesAlertarPorUsuario> tbNotificacionesAlertarPorUsuariousua { get; set; }
        public virtual ICollection<tbNotificacionesAlertarPorUsuario> tbNotificacionesAlertarPorUsuariousua_CreacionNavigation { get; set; }
        public virtual ICollection<tbNotificacionesAlertarPorUsuario> tbNotificacionesAlertarPorUsuariousua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbNotificaciones> tbNotificacionesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbNotificaciones> tbNotificacionesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPagos> tbPagosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPagos> tbPagosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPaises> tbPaisesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPaises> tbPaisesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPlanillaDetalles> tbPlanillaDetallesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPlanillaDetalles> tbPlanillaDetallesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPlanillas> tbPlanillasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPlanillas> tbPlanillasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPrestamos> tbPrestamosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPrestamos> tbPrestamosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPresupuestosDetalle> tbPresupuestosDetalleusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPresupuestosDetalle> tbPresupuestosDetalleusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPresupuestosEncabezado> tbPresupuestosEncabezadousua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPresupuestosEncabezado> tbPresupuestosEncabezadousua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbPresupuestosPorTasasCambio> tbPresupuestosPorTasasCambiousua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPresupuestosPorTasasCambio> tbPresupuestosPorTasasCambiousua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbProcesosVentas> tbProcesosVentasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbProcesosVentas> tbProcesosVentasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbProyectosConstruccionBienesRaices> tbProyectosConstruccionBienesRaicesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbProyectosConstruccionBienesRaices> tbProyectosConstruccionBienesRaicesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbProyectos> tbProyectosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbProyectos> tbProyectosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbReferenciasCeldas> tbReferenciasCeldasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbReferenciasCeldas> tbReferenciasCeldasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbRentaMaquinariasPorActividades> tbRentaMaquinariasPorActividadesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbRentaMaquinariasPorActividades> tbRentaMaquinariasPorActividadesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbRetrasos> tbRetrasosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbRetrasos> tbRetrasosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbSubcategorias> tbSubcategoriasusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbSubcategorias> tbSubcategoriasusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbTasasCambio> tbTasasCambiousua_CreacionNavigation { get; set; }
        public virtual ICollection<tbTasasCambio> tbTasasCambiousua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbTerrenos> tbTerrenosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbTerrenos> tbTerrenosusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbTiposDocumentos> tbTiposDocumentosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbTiposDocumentos> tbTiposDocumentosusua_MofificacionNavigation { get; set; }
        public virtual ICollection<tbTiposProyecto> tbTiposProyectousua_CreacionNavigation { get; set; }
        public virtual ICollection<tbTiposProyecto> tbTiposProyectousua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbTokens> tbTokens { get; set; }
        public virtual ICollection<tbUnidadesMedida> tbUnidadesMedidausua_CreacionNavigation { get; set; }
        public virtual ICollection<tbUnidadesMedida> tbUnidadesMedidausua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbViaticosDetalles> tbViaticosDetallesusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbViaticosDetalles> tbViaticosDetallesusua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbViaticosEncabezados> tbViaticosEncabezadosusua_CreacionNavigation { get; set; }
        public virtual ICollection<tbViaticosEncabezados> tbViaticosEncabezadosusua_ModificacionNavigation { get; set; }
    }
}