// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbViaticosDetalles_Bitacora
    {
        public int vide_Id { get; set; }
        public string vide_Descripcion { get; set; }
        public string vide_ImagenFactura { get; set; }
        public string vide_MontoGastado { get; set; }
        public int vien_Id { get; set; }
        public int cavi_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime vide_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? vide_FechaModificacion { get; set; }
        public decimal? vide_MontoReconocido { get; set; }
        public bool vide_Estado { get; set; }
        public string accion { get; set; }
    }
}