// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbViaticosDetalles
    {
        public int vide_Id { get; set; }
        public string vide_Descripcion { get; set; }
        public string vide_ImagenFactura { get; set; }
        public decimal? vide_MontoGastado { get; set; }
        public int vien_Id { get; set; }
        public int cavi_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime vide_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? vide_FechaModificacion { get; set; }
        public decimal? vide_MontoReconocido { get; set; }
        public bool? vide_Estado { get; set; }

        [NotMapped]
        public string usuaCreacion { get; set; }
        [NotMapped]
        public string usuaModificacion { get; set; }

        [NotMapped]
        public string Empleado { get; set; }
        [NotMapped]
        public int codigo { get; set; }
        [NotMapped]
        public string Proyecto { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModifica { get; set; }

        [NotMapped]
        public string vien_EstadoFacturas { get; set; }

        [NotMapped]
        public string cavi_Descripcion { get; set; }

        public virtual tbCategoriasViaticos cavi { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual tbViaticosEncabezados vien { get; set; }
    }
}