// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbViaticosEncabezados
    {
        public tbViaticosEncabezados()
        {
            tbViaticosDetalles = new HashSet<tbViaticosDetalles>();
        }

        public int vien_Id { get; set; }
        public decimal vien_MontoEstimado { get; set; }
        public decimal? vien_TotalGastado { get; set; }
        public DateTime vien_FechaEmicion { get; set; }
        public int empl_Id { get; set; }
        public int Proy_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime vien_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? vien_FechaModificacion { get; set; }
        public decimal? vien_TotalReconocido { get; set; }
        public bool? vien_Estado { get; set; }
        public bool? vien_EstadoFacturas { get; set; }

        [NotMapped]
        public string Empleado { get; set; }
        [NotMapped]
        public int codigo { get; set; }
        [NotMapped]
        public string Proyecto { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }
        [NotMapped]
        public string UsuarioModifica { get; set; }
        [NotMapped]
        public bool? usuarioEsAdm { get; set; }

        [NotMapped]
        public string cavi_Descripcion { get; set; }
        [NotMapped]
        public string vide_Descripcion { get; set; }
        [NotMapped]
        public string vide_ImagenFactura { get; set; }
        [NotMapped]
        public string vide_MontoGastado { get; set; }
        [NotMapped]
        public string vide_MontoReconocido { get; set; }

        public virtual tbProyectos Proy { get; set; }
        public virtual tbEmpleados empl { get; set; }
        public virtual tbUsuarios usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios usua_ModificacionNavigation { get; set; }
        public virtual ICollection<tbViaticosDetalles> tbViaticosDetalles { get; set; }
    }
}