// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SIGESPROC.Entities.Entities
{
    public partial class tbViaticosEncabezados_Bitacora
    {
        public int vien_Id { get; set; }
        public decimal vien_MontoEstimado { get; set; }
        public decimal? vien_TotalGastado { get; set; }
        public DateTime vien_FechaEmicion { get; set; }
        public int empl_Id { get; set; }
        public int Proy_Id { get; set; }
        public int usua_Creacion { get; set; }
        public DateTime vien_FechaCreacion { get; set; }
        public int? usua_Modificacion { get; set; }
        public DateTime? vien_FechaModificacion { get; set; }
        public decimal? vien_TotalReconocido { get; set; }
        public bool? vien_Estado { get; set; }
        public bool? vien_EstadoFacturas { get; set; }
        public string accion { get; set; }
    }
}